### PR TITLE
Bump version number to 1.3

### PR DESCRIPTION
**Pull request by matthijskooijman**
It would be great if you could merge this and create a tag, so the version with bugfixes can be downloaded through the library manager. Also, I'm finalizing my book and what to ship the exact library versions used, so it would be great if there is a released version, so I won't have to ship a patched 1.2 version, which will be confusing.

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Yes, I'll get to this soon-ish...

First, I want to look into #13, before tagging a release.  As I recall, that +16 was done only to generate an interrupt "soon".  But it's been quite a while since I've really worked on this code.  Any thoughts on that issue?

**Comment by PaulStoffregen** [comment]
In the meantime, it's very safe to assume the next tag will be 1.3.  :)

**Comment by matthijskooijman** [comment]
Thanks for responding :-)

> First, I want to look into #13, before tagging a release. As I recall, that +16 was done only to generate an interrupt "soon". But it's been quite a while since I've really worked on this code. Any thoughts on that issue?

Yeah, that's exactly what I gathered from reading the code while working on those bug fixes. I've added a comment to the issue explaining this.

**Comment by PaulStoffregen** [comment]
done

**Comment by matthijskooijman** [comment]
Thanks!

**Pull request closed without merging**
